name: asdmediumu
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  html: ^0.15.4
  http: ^1.2.1
  json_path: ^0.7.2
  google_generative_ai: ^0.4.6
  beautiful_soup_dart: ^0.3.0
  mysql1: ^0.20.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
